# Generated by Django 3.1.5 on 2021-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210201_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='colors',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
